AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateway that can be taken up and down to save money'

Resources:
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !ImportValue foundation-PublicSubnet1Id
      Tags:
        - Key: Name
          Value: Foundation NATGW

  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  NATGatewayId:
    Description: NAT Gateway ID
    Value: !Ref NATGateway
    Export:
      Name: !Sub "${AWS::StackName}-NATGatewayId"
