services:
  frps:
    image: snowdreamtech/frps:0.61.2
    container_name: frps
    restart: always
    volumes:
      - /home/ec2-user/frp/frps.toml:/etc/frp/frps.toml
      - /home/ec2-user/frp/certs:/certs:ro
      - /home/ec2-user/frp/generate_certs.sh:/generate_certs.sh
    expose:
      - "7000"    # Control port
      # - "7500"  # Dashboard
      #- "80"     # HTTP vhost
      #- "443"    # HTTPS vhost
    ports:
      - "7000:7000"            # Control port (TCP)
      - "7000:7000/udp"        # Control port (UDP/KCP)
      - "5000-5100:5000-5100"  # Range for TCP tunnels
    networks:
      - main
    labels:
      - "traefik.enable=true"

networks:
  main:
    external: true
