services:
  traefik:
    image: "traefik:v3.3.5"
    restart: always
    container_name: traefik
    networks: 
     - main
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/ec2-user/traefik/letsencrypt:/letsencrypt"
      - "/home/ec2-user/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    ports:
      - "80:80"
      - "443:443"
    environment:
      # AWS Route53 credentials
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_REGION=${AWS_REGION}"
      - "EMAIL=${EMAIL}"
      - "DOMAIN=${DOMAIN}"
      - "ADMIN_CIDR=${ADMIN_CIDR}"

networks:
  main:
    external: true
