services:
  traefik:
    image: "traefik:v3.3.5"
    restart: always
    container_name: traefik
    networks: 
     - main
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/ec2-user/traefik/letsencrypt:/letsencrypt"
      - "/home/ec2-user/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    ports:
      - "80:80"
      - "443:443"
    environment:
      # AWS Route53 credentials
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_REGION=${AWS_REGION}"
    labels:
      - "traefik.enable=true"
      # Dashboard configuration with wildcard cert
      - "traefik.http.routers.dashboard.rule=Host(`jobs.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.dashboard-ipwhitelist.ipwhitelist.sourcerange=${ADMIN_CIDR}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-ipwhitelist"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.dashboard-http.rule=Host(`jobs.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dashboard-http.middlewares=redirect-to-https"
      
      # Generate wildcard certificate
      - "traefik.http.routers.cert-wildcard.rule=Host(`wildcard-cert.${DOMAIN}`)" 
      - "traefik.http.routers.cert-wildcard.tls.certresolver=myresolver"
      - "traefik.http.routers.cert-wildcard.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.cert-wildcard.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.cert-wildcard.service=noop@internal"
      - "traefik.http.routers.cert-wildcard.entrypoints=websecure"
      
      - "EMAIL=${EMAIL}"
      - "DOMAIN=${DOMAIN}"
      - "ADMIN_CIDR=${ADMIN_CIDR}"

networks:
  main:
    external: true
